import type { Metadata } from "next";

/** Canonical site-wide constants used across metadata, sitemap, and structured data. */
export const SITE = {
  name: "ShareGratitude",
  url: "https://sharegratitude.com",
  locale: "en_GB",
  description:
    "Patients scan QR codes in hospitals to send thank-you messages directly to the healthcare staff who cared for them. No account needed.",
} as const;

type PageMetaInput = {
  /** Bare page title — the " | ShareGratitude" suffix is added via the title template. */
  title: string;
  description: string;
  /** Route path, e.g. "/about". Defaults to the home page. */
  path?: string;
};

/**
 * Builds a complete, per-page `Metadata` object: title, description, canonical
 * URL, and Open Graph / Twitter cards. Open Graph and Twitter titles include the
 * brand suffix explicitly (templates don't apply to those fields).
 */
/** Generated by app/opengraph-image.tsx (1200×630). Resolved against metadataBase. */
const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "ShareGratitude — Thank the healthcare staff who cared for you",
};

export function pageMetadata({ title, description, path = "/" }: PageMetaInput): Metadata {
  const url = path === "/" ? SITE.url : `${SITE.url}${path}`;
  const ogTitle = `${title} | ${SITE.name}`;

  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      siteName: SITE.name,
      locale: SITE.locale,
      url,
      title: ogTitle,
      description,
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: ogTitle,
      description,
      images: [OG_IMAGE.url],
    },
  };
}
